
CREATE DATABASE pagari;
USE pagari;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100),email VARCHAR(100),password VARCHAR(255));
CREATE TABLE foods(id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100),gula INT);
CREATE TABLE blood_sugar(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,nilai INT,tanggal DATE);
CREATE TABLE education(id INT AUTO_INCREMENT PRIMARY KEY,judul VARCHAR(200),konten TEXT);
CREATE TABLE user_activity(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,aktivitas VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
